name: ESharing

settings:
  base:
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: 'YES'

options:
  minimumXcodeGenVersion: 2.32
  bundleIdPrefix: com.esharing
  generateEmptyDirectories: true
  deploymentTarget: 
    iOS: "15.0"

packages:
  ESharingRoot:
    path: Modules/Modules

targets:
  ESharingApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    dependencies:
      - package: ESharingRoot

    settings:
      base:
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1
        SWIFT_VERSION: 5.7
        OTHER_LDFLAGS: "-Xlinker -interposable -Xlinker -undefined -Xlinker dynamic_lookup"
        INFOPLIST_FILE: "Resources/Info.plist"

    info:
      path: Resources/Info.plist
      properties:
        CFBundleName: ESharingApp
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait 
        CFBundleDocumentTypes:
          - 
              CFBundleTypeName: MKDirectionsRequest
              LSItemContentTypes: [com.apple.maps.directionsrequest]
        MKDirectionsApplicationSupportedModes:
          - MKDirectionsModeBike
          - MKDirectionsModePedestrian
        NSLocationWhenInUseUsageDescription:
          - ESharing uses your location to provide vehicles near you
        NSLocationAlwaysAndWhenInUseUsageDescription:
          - ESharing uses your location to provide vehicles near you

    sources:
      - path: Code
        # buildPhase: sources
      - path: Resources
        # buildPhase: resources

schemes:
  ESharingApp:
    build:
      targets:
        ESharingApp: all
      parallelizeBuild: true
      buildImplicitDependencies: true
    # run:
    #   launchAutomaticallySubstyle: 2